name: weather
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
linter:
  rules:
    - non_constant_identifier_names
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.2
  http: ^0.13.6
  provider: ^6.0.5
  intl: ^0.18.1
  font_awesome_flutter: ^10.4.0
  fl_chart: ^0.62.0
  flutter_dotenv: ^5.0.2
  percent_indicator: ^4.2.3
  country_icons: ^2.0.2
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  androind: true
  ios: true
  image_path: "assets/logo1.png"

flutter:

  uses-material-design: true
  assets:
    - assets/weather.json
    - assets/city.json
    - assets/air.json
    - assets/logo.png
    - assets/icons/wind.json
    - assets/icons/water.json
    - assets/icons/rain.json
    - assets/icons/star.json
    - assets/animations/1.json
    - assets/animations/2.json
    - assets/animations/3.json
    - assets/animations/4.json
    - assets/animations/5.json
    - assets/animations/6.json
    - assets/animations/7.json
    - assets/animations/8.json
    - assets/animations/9.json
    - assets/animations/10.json
    - assets/animations/11.json
    - assets/animations/12.json
    - assets/animations/13.json
    - assets/animations/14.json
    - assets/animations/15.json
    - assets/loadings/1.json
    - assets/loadings/2.json
    - assets/loadings/3.json
    - assets/loadings/4.json
    - assets/loadings/5.json
    - .env